jira_project:
  type: 'jira'
  host: "host name"
  user: "username"
  passwd: "Password"
  api_key: "API_key"
  project: "Project key"
  component: "Some Pipeline component"
  issue_level: "Task"
  assign_to: "Set assignee for the ticket or set default within Jira prroject."
  priority: "Medium"
  default_email_list: "Set a default email to use if you get nothing back from email."
  database_email_list: "database endpoint that returns a list of emails."
mnt-issue_log:
  type: 'log_file'
  path: 'path to store stats and log'
  component: ''
  default_email_list: ""
  database_email_list: ""
project_2-jira:
  type: ''
  host: ""
  user: ""
  passwd: ""
  project: ""
  component: ""
  issue_level: ""
  default_email_list: ""
  database_email_list: ""
project_3-jira:
  type: ''
  host: ''
  user: ""
  passwd: ''
  project: ''
  component: ""
  issue_level: ""
  default_email_list: ""
  database_email_list: ""
mnt-issue_log:
  type: 'log_file'
  path: 'path to store stats and log'
  component: 'mnt-issue_log'
  default_email_list: ""
  database_email_list: "" 
